SwapUp-dApp/Backend-v2

src/api/controllers/walletController.js
src/api/routes/index.js
src/api/routes/walletRoutes.js
src/utils/alchemy.js

wallet --> dev: token breakdown by wallet id endpoint created

wallet --> dev: token breakdown by wallet id endpoint created

---

src/api/controllers/walletController.js

token breakdown endpoint updated

wallet --> main: token breakdown endpoint updated

---

src/api/controllers/nftController.js
src/api/routes/nftRoutes.js

wallet --> main: collection by wallet id endpoint created

wallet --> main: collection by wallet id endpoint created

---

src/api/controllers/nftController.js
src/utils/alchemy.js

wallet --> main: collection endpoint fix and using sepolia network for testing subname minting

wallet --> main: collection endpoint fix and using sepolia network for testing subname minting

---

package-lock.json
package.json
src/api/controllers/twitterController.js
src/api/routes/index.js
src/api/routes/openSwapRouter.js
src/api/routes/twitterRouter.js
src/server.js

twitter-post --> main: twitter post is being created on behalf of user

twitter-post --> main: twitter post is being created on behalf of user

---

src/api/controllers/userController.js
src/api/controllers/walletController.js
src/api/routes/index.js
src/api/routes/userRouter.js
src/api/routes/walletRoutes.js
src/database/migrations/20240614125630-fresh-start.js
src/database/models/index.js
src/database/models/user.js

user --> main: user: creaing swapup new user by wallet id

user --> main: user: creaing swapup new user by wallet id

---

src/api/controllers/openSwapController.js
src/api/controllers/swapController.js
src/api/routes/openSwapRouter.js
src/api/routes/swapsRoutes.js

swap-details-fixes --> main: swap details endpoint is updated based on trade and open trade id

swap-details-fixes --> main: swap details endpoint is updated based on trade and open trade id

---

package-lock.json
package.json
src/api/controllers/twitterController.js
src/api/routes/twitterRouter.js
src/api/utils/helpers.js

twitter-post --> main: twitter post method updated with puppeteer package

twitter-post --> main: twitter post method updated with puppeteer package

---

.env
.gitignore
package-lock.json
package.json
sequelizeMeta.json
src/api/controllers/blobController.js
src/api/controllers/twitterController.js
src/api/controllers/userController.js
src/api/routes/userRouter.js
src/database/migrations/20240910104139-add-profile-columns-user.js
src/database/models/user.js

user-profile: blob storage upload and delete image endpoints added and new columns added in Users table

user --> main: user-profile: blob storage upload and delete image endpoints added

---

.gitignore
src/api/controllers/blobController.js
src/api/controllers/openSwapController.js
src/api/controllers/swapController.js
src/api/controllers/userController.js
src/api/routes/userRouter.js
src/api/utils/constants.js
src/api/utils/userTagsUpdater.js

user --> main: user details endpoints, points and trader tags logic

user --> main: user details endpoints, points and trader tags logic

---

src/api/controllers/userController.js

user --> main: update user points endpoint variable name updated / fixed

user --> main: update user points endpoint variable name updated / fixed

---

sequelizeMeta.json
src/api/controllers/userController.js
src/database/migrations/20240930115440-update-points-column-type.js
src/database/models/user.js

user --> main: user: points system endpoint & logic updated

user --> main: user: points system endpoint & logic updated

---

.env
package-lock.json
package.json
sequelizeMeta.json
src/api/controllers/paymentController.js
src/api/routes/index.js
src/api/routes/nftRoutes.js
src/api/routes/paymentRouter.js
src/api/utils/constants.js
src/api/utils/dtos.js
src/api/utils/helpers.js
src/database/migrations/20241014085150-create-payments.js
src/database/models/index.js
src/database/models/payments.js
src/errors/customError.js
src/server.js
src/service/thirdparty.service.js

payment-integration --> main: thirdweb payment webhook integration, save payment data in db and manual subname mint

payment-integration --> main: thirdweb payment webhook integration, save payment data in db and manual subname mint

---

src/api/controllers/paymentController.js

payment-integration --> main: paymentTriggeredFrom check added in webhook endpoint

payment-integration --> main: paymentTriggeredFrom check added in webhook endpoint

---

src/api/controllers/smartContractController.js
src/api/controllers/userController.js
src/api/utils/helpers.js
src/database/models/index.js

smart-account --> main: new smart account generation process refactored

smart-account --> main: new smart account generation process refactored

---

sequelizeMeta.json
src/api/controllers/openSwapController.js
src/api/controllers/swapController.js
src/api/utils/helpers.js
src/database/config.js
src/database/migrations/20241121094500-rename-proposal-column-in-notifications.js
src/database/models/notifications.js

notification-fixes --> main: notification logic fixes and columns updated

notification-fixes --> main: notification logic fixes and columns updated

---

src/api/controllers/currenciesController.js
src/api/controllers/paymentController.js
src/api/controllers/treasuryController.js
src/api/controllers/walletController.js
src/api/routes/treasuryRouter.js
src/api/utils/helpers.js
src/constants/params.js

subname-minting --> main: treasury balance endpoints and other small fixes

subname-minting --> main: treasury balance endpoints and other small fixes

---

sequelizeMeta.json
src/api/controllers/currenciesController.js
src/api/controllers/manageController.js
src/api/controllers/paymentController.js
src/api/controllers/smartContractController.js
src/api/controllers/subnameController.js
src/api/utils/constants.js
src/api/utils/helpers.js
src/api/utils/subnameMinting.js
src/database/migrations/20241221151502-add-subnameCharges-to-subscriptionTokens.js
src/database/models/subscriptionTokens.js

subname-miniting --> main: Payment mode subscription tokens added in subname minting flow and  other fixes

subname-miniting --> main: Payment mode subscription tokens added in subname minting flow and  other fixes

---

src/api/controllers/analyticsController.js

traders-and-members --> main: top traders endpoint complete swap check fixed

traders-and-members --> main: top traders endpoint complete swap check fixed

---

src/api/controllers/analyticsController.js

analytics --> main: top traders endpoint null wallet id issue fixed

analytics --> main: top traders endpoint null wallet id issue fixed

---

src/api/controllers/analyticsController.js
src/api/controllers/currenciesController.js
src/api/routes/analyticsRouter.js
src/api/utils/currencies.js

analytics --> main: trending tokens and trending token pairs endpoints added

analytics --> main: trending tokens and trending token pairs endpoints added

---

src/api/controllers/walletController.js

wallet-breakdown-fixes --> main: token breakdown by wallet id fixes

wallet-breakdown-fixes --> main: token breakdown by wallet id fixes

---

src/api/utils/subnameMinting.js

subname-records --> main: text records & minter address added wile minting subdomain

subname-records --> main: text records & minter address added wile minting subdomain

---

sequelizeMeta.json
src/api/controllers/analyticsController.js
src/api/controllers/nftController.js
src/api/controllers/subnameController.js
src/api/routes/analyticsRouter.js
src/api/utils/nft.js
src/api/utils/subnameMinting.js
src/api/utils/userTagsUpdater.js
src/database/migrations/20250222011632-create-subnames-table.js
src/database/models/index.js
src/database/models/subnames.js

subname-table --> main: subnames table added & new member updating after minting subname

subname-table --> main: subnames table added & new member updating after minting subname
